version: '3'

services:
  db_jurishand:
    image: mysql:8.0.32
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=jurishand
  api_jurishand:
    build: .
    ports:
      - '3001:3001'
    restart: always
    depends_on:
      - db_jurishand
